src/Entity/User.php
<?php

namespace App\Entity;

use Symfony\Component\Security\Core\User\UserInterface;

class User implements UserInterface
{
    /** @var int */
    private $id;
    /** @var string */
    private $email;
    /** @var string */
    private $password;
    /** @var string[] */
    private $roles;
    /** @var string */
    private $salt;

    public function __construct($email)
    {
        $this->email = $email;
        $this->roles = ['ROLE_USER'];
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }


    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * @param string[] $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }


    public function addRole(string $role)
    {
        $this->roles[] = $role;
    }

    public function hasRole(string $role): bool
    {
        return (in_array($role, $this->roles));
    }

    public function removeRole(string $role)
    {
        if (array_key_exists($role, $this->roles))
        {
            unset($this->roles[$role]);
        }
    }

    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    public function getSalt()
    {
        return $this->salt;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/layout.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Mamandine - In cookies we trust</title>
    <link rel="stylesheet" href="css/style.css" media="all" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ path('app_cake_list') }}">Mamandine</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if is_granted('ROLE_ADMIN') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ path('app_cake_create') }}">Create cake</a>
            </li>
            {% endif %}
            {% if is_granted('ROLE_USER') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ path('app_security_logout') }}">{{ 'common.logout'|trans }}</a>
            </li>
            <li class="nav-item">
                <span class="nav-link disabled">{{ app.user.username }}</span>
            </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('app_security_login') }}">{{ 'common.login'|trans }}</a>
                </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
{% if app.session.flashbag.peekAll %}
    <div id="container">
        {% for name, messages in app.session.flashbag.all %}
            {% for message in messages %}
                <div class="alert alert-{{ name }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endif %}
<div id="container">
    {% block content %}
    {% endblock %}
</div>
<div class="navbar navbar-light">
    <div class="container">
        <p class="navbar-text pull-left">Mamandine - In cookies we trust.</p>
    </div>
</div>
</body>
</html>